# Licensed to Elasticsearch B.V. under one or more contributor
# license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright
# ownership. Elasticsearch B.V. licenses this file to you under
# the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

require_relative '../framework/fixture'
require_relative '../framework/settings'
require_relative '../services/logstash_service'
require_relative '../framework/helpers'
require_relative '../framework/cert_helpers'
require "logstash/devutils/rspec/spec_helper"
require "elasticsearch"
require "fileutils"
require "stud/temporary"
require "yaml"

# Probe test: verifies that a dynamically-generated PKCS12 truststore (built
# via the Java KeyStore API) allows the elasticsearch output plugin to connect
# and ingest events over TLS.
#
# If ingestion is not observed within 60 seconds the test fails with a clear
# message. Both Logstash (after(:each)) and Elasticsearch (after(:all)) are
# stopped even when the test is stuck, so no background processes are leaked.
#
# On failure, switch approach to static keystores generated by openssl+keytool
# (see qa/integration/fixtures/webserver_certs/generate.sh for the pattern).
describe "ES output truststore: PKCS12 truststore ingestion probe", :skip_fips do
  TRUSTSTORE_PASSWORD = "changeit"
  INGEST_TIMEOUT_SECS = 60

  def write_pipelines_yml(settings_dir, pipelines)
    IO.write(File.join(settings_dir, "pipelines.yml"), pipelines.to_yaml)
  end

  before(:all) do
    @cert_dir = Stud::Temporary.directory

    @ca_key, @ca_cert = generate_ca
    es_server_key, es_server_cert = generate_leaf(@ca_key, @ca_cert)
    write_cert_pair(@cert_dir, "es-server", es_server_key, es_server_cert)
    File.write(File.join(@cert_dir, "es-ca.crt"), @ca_cert.to_pem)

    ENV["ES_TLS_CERT"] = File.join(@cert_dir, "es-server.crt")
    ENV["ES_TLS_KEY"]  = File.join(@cert_dir, "es-server.key")
    ENV["ES_TLS_CA"]   = File.join(@cert_dir, "es-ca.crt")

    @fixture = Fixture.new(__FILE__)
  end

  # Stops ES and cleans up temp certs regardless of test outcome.
  after(:all) do
    @fixture.teardown
    ENV.delete("ES_TLS_CERT")
    ENV.delete("ES_TLS_KEY")
    ENV.delete("ES_TLS_CA")
    FileUtils.rm_rf(@cert_dir) if @cert_dir && Dir.exist?(@cert_dir)
  end

  let(:logstash_service) { @fixture.get_service("logstash") }
  let(:settings_dir)     { Stud::Temporary.directory }
  let(:work_dir)         { Stud::Temporary.directory }

  # Stops the Logstash process regardless of test outcome, including timeouts.
  after(:each) { logstash_service.teardown }

  def es_client
    @fixture.get_service("elasticsearch_tls").get_client
  end

  it "ingests events to ES using ssl_truststore_path" do
    index_name    = "truststore-ingest-test"
    truststore_path = File.join(work_dir, "es-truststore.p12")
    create_truststore(@ca_cert, truststore_path, TRUSTSTORE_PASSWORD)

    write_pipelines_yml(settings_dir, [{
      "pipeline.id"   => "main",
      "config.string" => <<~CFG
        input  { generator { count => 0 } }
        output {
          elasticsearch {
            hosts => ["https://localhost:9200"]
            ssl_enabled => true
            ssl_truststore_path => "#{truststore_path}"
            ssl_truststore_type => "pkcs12"
            ssl_truststore_password => "#{TRUSTSTORE_PASSWORD}"
            user => "esadmin"
            password => "esadmin123"
            index => "#{index_name}"
          }
        }
      CFG
    }])

    logstash_service.spawn_logstash(
      "--path.settings", settings_dir,
      "--path.data", File.join(work_dir, "data")
    )
    logstash_service.wait_for_logstash

    Stud.try(INGEST_TIMEOUT_SECS.times, [StandardError]) do
      sleep 1
      count = es_client.count(index: index_name)["count"].to_i rescue 0
      raise "No docs in '#{index_name}' after #{INGEST_TIMEOUT_SECS}s. " \
            "Dynamic PKCS12 truststore approach may be broken. " \
            "Consider switching to openssl+keytool pre-generated keystores." \
        unless count >= 1
    end
  end
end
